language: python
python:
  - "3.6"
# command to run tests
script:
  - bash scripts/run_tests.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    - bash scripts/tag.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
